# AUTO_DELETE 10 year template
RET_POLICY_NAME=AUTO_DELETE_10Y

retention.type=FIXED_TIME
retention.enabled=false

expiration.enabled=true
expiration.age=10y
expiration.action=AUTO_DELETE

auto-delete.schedule=0 2 * * *
auto-delete.commit-count=100
auto-delete.max-items=5000
auto-delete.max-duration=120
auto-delete.force-checkin=true
